const data = {
    products: [
        {   
            _id: '1',
            name: "Brown Leather",
            slug: 'brown-leather-shoe',
            category: 'Sneakers',
            image: '/images/brown.jpg',
            price: 120,
            couuntInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality',
            countInStock: 4,
            
        },
        {   
            _id: '2',
            name: "Red Leather",
            slug: 'red-leather-shoe',
            category: 'Sneakers',
            image: '/images/prime.jpg',
            price: 150,
            couuntInStock: 16,
            brand: 'Adidas',
            rating: 5,
            numReviews: 15,
            description: 'High quality',
            countInStock: 0,
        },
        {   
            _id: '3',
            name: "Black Leather",
            slug: 'black-leather-shoe',
            category: 'Sneakers',
            image: '/images/black.jpg',
            price: 190,
            couuntInStock: 5,
            brand: 'Puma',
            rating: 7.5,
            numReviews: 20,
            description: 'High quality',
            countInStock: 8
        },
        {   
            _id: '4',
            name: "Red Leather",
            slug: 'red-leather-shoe',
            category: 'Sneakers',
            image: '/images/prime.jpg',
            price: 150,
            couuntInStock: 16,
            brand: 'Adidas',
            rating: 5,
            numReviews: 15,
            description: 'High quality',
            countInStock: 0,
        },
        {   
            _id: '5',
            name: "Black Leather",
            slug: 'black-leather-shoe',
            category: 'Sneakers',
            image: '/images/black.jpg',
            price: 190,
            couuntInStock: 5,
            brand: 'Puma',
            rating: 7.5,
            numReviews: 20,
            description: 'High quality',
            countInStock: 8
        },
        {   
            _id: '6',
            name: "Brown Leather",
            slug: 'brown-leather-shoe',
            category: 'Sneakers',
            image: '/images/brown.jpg',
            price: 120,
            couuntInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality',
            countInStock: 4,
            
        },
        {   
            _id: '7',
            name: "Red Leather",
            slug: 'red-leather-shoe',
            category: 'Sneakers',
            image: '/images/prime.jpg',
            price: 150,
            couuntInStock: 16,
            brand: 'Adidas',
            rating: 5,
            numReviews: 15,
            description: 'High quality',
            countInStock: 0,
        },
        {   
            _id: '8',
            name: "Black Leather",
            slug: 'black-leather-shoe',
            category: 'Sneakers',
            image: '/images/black.jpg',
            price: 190,
            couuntInStock: 5,
            brand: 'Puma',
            rating: 7.5,
            numReviews: 20,
            description: 'High quality',
            countInStock: 8
        },
        {   
            _id: '9',
            name: "Red Leather",
            slug: 'red-leather-shoe',
            category: 'Sneakers',
            image: '/images/prime.jpg',
            price: 150,
            couuntInStock: 16,
            brand: 'Adidas',
            rating: 5,
            numReviews: 15,
            description: 'High quality',
            countInStock: 0,
        },
    ]
}

export default data;